name: Run Tests

on:
  push:
    branches:
      - main
      - 2D_sim
      - yml_test_branch
  pull_request:
    branches:
      - main
      - 2D_sim
      - yml_test_branch

jobs:
  test:
    strategy:
        matrix:
          platform: [ubuntu-latest]
          python-version: ["3.13.3"]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
    
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          activate-environment: fenicsx-env
        
      - name: Install DOLFINx with MPICH (Unix-like)
        run: conda install -c conda-forge fenics-dolfinx mpich pyvista

      - name: Install dependencies
        run: pip install -e .

      - name: Install test dependencies
        run: pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true  # Ensure failure if upload fails
